#!/usr/bin/env bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2015, Joyent, Inc.
#

# Run a single test of any type.

if [ "$TRACE" != "" ]; then
    export PS4='${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi
set -o errexit
set -o pipefail


TOP=$(cd $(dirname $0)/../; pwd)
NODE_INSTALL=$TOP/build/node
TAPE=$TOP/node_modules/.bin/tape
UNAME=$(uname -s)

export DOCKER_UUID="$(vmadm lookup -j alias=docker0 | json 0.uuid)"
export DOCKER_URL="https://$(vmadm lookup -j alias=docker0 | json 0.nics | json -c 'this.nic_tag==="external"' 0.ip):2376"
export FWAPI_URL="http://$(vmadm lookup -j alias=fwapi0 | json 0.nics | json -c 'this.nic_tag==="admin"' 0.ip)"
export VMAPI_URL="http://$(vmadm lookup -j alias=vmapi0 | json 0.nics | json -c 'this.nic_tag==="admin"' 0.ip)"
export SAPI_URL="http://$(vmadm lookup -j alias=sapi0 | json 0.nics | json -c 'this.nic_tag==="admin"' 0.ip)"

echo "# Test config:"
echo "#  DOCKER_UUID=${DOCKER_UUID}"
echo "#  DOCKER_URL=${DOCKER_URL}"
echo "#  FWAPI_URL=${FWAPI_URL}"
echo "#  VMAPI_URL=${VMAPI_URL}"
echo "#  SAPI_URL=${SAPI_URL}"

guard_file=/lib/sdc/.sdc-test-no-production-data
if [[ $UNAME == "SunOS" ]] && [[ ! -f "$guard_file" ]]; then
    cat <<EOF
To run this test you must create the file:

    $guard_file

after ensuring you have no production data on this SDC.
EOF
    exit 2
fi

PATH=$NODE_INSTALL/bin:$PATH $TAPE $1
