#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

#
# Rsync this the master in this working copy to the install on the given HN.
#

#set -o xtrace
set -o errexit

TOP=$(cd $(dirname $0)/../; pwd)
NODE=$1
if [[ -z "$NODE" ]]; then
    echo 'usage: rsync-to NODE'
    exit 1
fi
BASEDIR=/opt/smartdc/docker.js

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts="--exclude *.node --exclude build"
else
    # Clean node_modules everytime.
    ssh $NODE rm -rf $BASEDIR/node_modules
fi

for name in smf lib node_modules package.json; do
    if [[ -d ${TOP}/$name ]]; then
        rsync -av ${TOP}/$name/ $NODE:$BASEDIR/$name/ $extraOpts
    else
        rsync -av ${TOP}/$name $NODE:$BASEDIR/$name $extraOpts
    fi
done

ssh $NODE '
    if [[ "$(svcs -Ho state docker)" == "maintenance" ]]; then
        svcadm clear docker;
    else
        svcadm restart docker;
    fi
    '
