#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

#
# Rsync the master in this working copy to the install on the given HN.
#

#set -o xtrace
set -o errexit

TOP=$(cd $(dirname $0)/../; pwd)
NODE=$1

if [[ -z "$DOCKER_ZONE" ]]; then
    DOCKER_ZONE=$(ssh $NODE "/opt/smartdc/bin/sdc-vmapi /vms" 2>/dev/null \
        | json -H -c 'this.tags && this.tags.smartdc_role === "docker"' \
            -c 'this.state === "running"' 0.uuid)
fi
echo "DOCKER_ZONE: $DOCKER_ZONE"

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts="--exclude *.node --exclude build"
else
    # Clean node_modules everytime.
    ssh $NODE rm -rf /zones/$DOCKER_ZONE/root/opt/smartdc/docker/node_modules
fi

rsync -av ${TOP}/ \
    $NODE:/zones/$DOCKER_ZONE/root/opt/smartdc/docker/ \
    $extraOpts \
    --exclude .git/ \
    --exclude /etc/config.json \
    --exclude /deps/ \
    --exclude /doc/ \
    --exclude /tools/ \
    --exclude /tmp/

state=$(ssh ${NODE} svcs -z ${DOCKER_ZONE} -H -o state docker)
if [[ "$state" == "maintenance" ]]; then
    ssh ${NODE} svcadm -z ${DOCKER_ZONE} clear docker
else
    ssh ${NODE} svcadm -z ${DOCKER_ZONE} restart docker
fi
ssh ${NODE} svcadm -z ${DOCKER_ZONE} restart config-agent
